apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
      - name: reviews-container
        image: registry.digitalocean.com/mi-ecommerce-reviews-proyecto/review-service:fresco
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: registry-mi-ecommerce-reviews-proyecto
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-service
spec:
  type: LoadBalancer
  selector:
    app: reviews
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000