name: CI/CD Reviews Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build Docker Image
        # Aquí le decimos explícitamente que el contexto es la carpeta reviews
        run: docker build -t registry.digitalocean.com/mi-ecommerce-reviews-proyecto/review-service:${{ github.sha }} ./Service/reviews

      - name: Log in to DigitalOcean Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push Image to Registry
        run: docker push registry.digitalocean.com/mi-ecommerce-reviews-proyecto/review-service:${{ github.sha }}

      - name: Update Kubernetes Deployment
        run: |
          doctl kubernetes cluster kubeconfig save ${{ secrets.DOKS_CLUSTER_ID }}
          # Usamos la ruta completa para encontrar el deployment.yaml
          sed -i 's|image:.*|image: registry.digitalocean.com/mi-ecommerce-reviews-proyecto/review-service:${{ github.sha }}|' ./Service/reviews/deployment.yaml
          kubectl apply -f ./Service/reviews/deployment.yaml